name: Questionarium

on:
  push:
    branches:
      - main  # This triggers the workflow when you push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Runs the workflow on a Linux machine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checks out your code so the workflow can access it

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20  # Specifies the Go version

      - name: Install Dependencies
        run: go mod tidy  # Installs necessary Go packages

      - name: Run Tests
        run: go test ./...  # Runs your Go tests

      - name: Build Application
        run: go build -o myapp ./cmd/myapp  # Builds your application

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1  # Adjust to your AWS region
        run: |
          aws s3 cp myapp s3://my-bucket/myapp --region $AWS_REGION
